version: "3.8"

services:
  telegram_bot:
    build: .
    container_name: callsum_telegram_bot_local
    env_file:
      - .env
    volumes:
      - ./telegram_bot:/app/telegram_bot
    working_dir: /app/telegram_bot
    command: ["python", "bot_local.py"]
    restart: unless-stopped
